// Typelizer digest 32dad5defc9cfeaf74be4a9d56cc875e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type BaseUser = {
  id: number;
  username: string | null;
  email: string;
}

export default BaseUser;
