// Typelizer digest f0662adfe341a52c43c313517a478e32
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type CategoryBase = {
  id: number;
  name: string | null;
  createdAt: string;
  topicsCount: number;
}

export default CategoryBase;
