// Typelizer digest 9ae83d4a343d09eb4de1daf1be1f26cf
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Category} from '@/types'

type CategoriesShow = {
  category: Category;
}

export default CategoriesShow;
