// Typelizer digest d3835551a0775fb20ab490a2c541ef07
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Topic} from '@/types'

type Category = {
  id: number;
  name: string | null;
  createdAt: string;
  topicsCount: number;
  topics: Array<Topic>;
}

export default Category;
