// Typelizer digest 8ad461341ac7ed37d6881e470dda0626
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {User} from '@/types'

type Message = {
  id: number;
  body: string | null;
  createdAt: string;
  user: User;
}

export default Message;
