// Typelizer digest 27c60f71b22d669082bd2bb7bf76b4dc
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {BaseUser, CategoryBase} from '@/types'

type SharedProps = {
  currentUser: BaseUser;
  categories: Array<CategoryBase>;
}

export default SharedProps;
