// Typelizer digest 552476872864e9dd13e737980db7b95e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Topic} from '@/types'

type TopicsShow = {
  topic: Topic;
}

export default TopicsShow;
