// Typelizer digest a4cee2b67b01140468f8c7fabf9dd183
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Topic} from '@/types'

type TopicsIndex = {
  topics: Array<Topic>;
}

export default TopicsIndex;
