// Typelizer digest 53bd6ed0f74584d0c6b981327487bfac
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {CategoryBase, User, Message} from '@/types'

type Topic = {
  id: number;
  title: string | null;
  category: CategoryBase;
  user: User;
  messages: Array<Message>;
}

export default Topic;
