// Typelizer digest f7bfa305b08e20e442bb37ded2eb6431
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: number;
  username: string | null;
  email: string;
  aboutMe: string | null;
  topicsCount: number;
  messagesCount: number;
}

export default User;
